FROM ghcr.io/astral-sh/uv:python3.10-bookworm-slim

WORKDIR /app
COPY . .

RUN uv sync && uv pip install --system -e .

ENV PYTHONUNBUFFERED=.

ENTRYPOINT [ "uv", "run", "gunicorn", "-b", "0.0.0.0:6666", "tlrl.api:api"]
