FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir -U pip setuptools wheel

COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN pip install --no-cache-dir -e .
# TODO does not actually use python-readability
RUN pip install --no-cache-dir -e python-readability

ENV PYTHONUNBUFFERED=.

ENTRYPOINT [ "gunicorn", "-b", "0.0.0.0:6666", "yesterdays_hackernews.api:api"]
